# Generated by Django 4.0.3 on 2022-03-12 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner_restaurent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurent',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='restaurent',
            old_name='phone_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='restaurent',
            name='name',
        ),
        migrations.AddField(
            model_name='restaurent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Restaurent_owner',
        ),
    ]
