# Generated by Django 4.0.3 on 2022-03-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0002_rename_email_address_restaurent_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurent_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurent',
            name='restaurent_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner_restaurent.restaurent_owner'),
        ),
    ]
