# Generated by Django 4.0.3 on 2022-03-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0003_restaurent_owner_restaurent_restaurent_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
