# Generated by Django 4.0.3 on 2022-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0004_restaurent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='menu',
            field=models.ManyToManyField(to='partner_restaurent.menuitem'),
        ),
    ]
