# Generated by Django 4.0.3 on 2022-03-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0007_restaurent_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurent',
            name='menu',
        ),
    ]
