# Generated by Django 4.0.3 on 2022-03-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0008_remove_restaurent_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner_restaurent.menuitem'),
        ),
    ]
