# Generated by Django 4.0.3 on 2022-03-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0011_menuitem_restaurent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurent',
        ),
    ]
