# Generated by Django 4.0.3 on 2022-03-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0013_menuitem_restaurent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='Type_cuisine',
        ),
    ]
