# Generated by Django 4.0.3 on 2022-03-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0014_remove_menuitem_type_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurent',
        ),
        migrations.AddField(
            model_name='restaurent',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner_restaurent.menuitem'),
        ),
    ]
