# Generated by Django 4.0.3 on 2022-03-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0015_remove_menuitem_restaurent_restaurent_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurent',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner_restaurent.restaurent'),
        ),
    ]
