# Generated by Django 4.0.3 on 2022-03-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0016_remove_restaurent_menu_menuitem_restaurent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurent',
            old_name='type_resturent',
            new_name='type_restaurent',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_img'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='restaurent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner_restaurent.restaurent'),
        ),
    ]
