# Generated by Django 4.0.3 on 2022-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0017_rename_type_resturent_restaurent_type_restaurent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurent_photos'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dish_photos'),
        ),
    ]
