# Generated by Django 4.0.3 on 2022-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0018_restaurent_logo_alter_menuitem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurent_logo'),
        ),
    ]
