# Generated by Django 4.0.3 on 2022-03-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0020_orderdetails_remove_order_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='restaurent',
        ),
    ]
