# Generated by Django 4.0.3 on 2022-04-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0021_rename_restaurant_order_restaurent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='restaurent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res', to='partner_restaurent.restaurent'),
        ),
    ]
