# Generated by Django 4.0.3 on 2022-04-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_delete_shippingaddress'),
        ('partner_restaurent', '0022_alter_menuitem_restaurent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.OneToOneField(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
    ]
