# Generated by Django 4.0.3 on 2022-04-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0023_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurent',
            name='type_restaurent',
        ),
    ]
