# Generated by Django 4.0.3 on 2022-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0024_remove_restaurent_type_restaurent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent',
            name='jour_desponibilite',
            field=models.CharField(blank=True, choices=[('Everyday', 'Everyday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Sunday', 'Sunday')], max_length=100, null=True),
        ),
    ]
