# Generated by Django 4.0.3 on 2022-05-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0025_alter_restaurent_jour_desponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='lat',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restaurent',
            name='long',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
