# Generated by Django 4.0.3 on 2022-05-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0026_restaurent_lat_restaurent_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurent',
            name='address_exacte',
        ),
    ]
