# Generated by Django 4.0.3 on 2022-05-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0027_remove_restaurent_address_exacte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type_cuisine',
        ),
        migrations.DeleteModel(
            name='Type_Resturent',
        ),
    ]
