# Generated by Django 4.0.3 on 2022-04-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_pass',
            field=models.CharField(blank=True, default='', max_length=130),
        ),
    ]
