# Generated by Django 4.0.3 on 2022-05-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_delete_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='address',
            name='long',
        ),
        migrations.AddField(
            model_name='address',
            name='commune',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='wilaya',
            field=models.TextField(blank=True, null=True),
        ),
    ]
