# Generated by Django 4.0.3 on 2022-05-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_address_lat_remove_address_long_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
