# Generated by Django 4.0.3 on 2022-03-30 17:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_restaurent', '0019_alter_restaurent_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_man', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveyMan',
            new_name='DeliveryMan',
        ),
    ]
