# Generated by Django 4.0.3 on 2022-04-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_man', '0002_rename_deliveyman_deliveryman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='adresse_exacte',
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
