# Generated by Django 4.0.3 on 2022-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_man', '0003_remove_deliveryman_adresse_exacte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='date_naissance',
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='driver_avatars'),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='plate_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
