# Generated by Django 4.0.3 on 2022-04-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_man', '0004_remove_deliveryman_date_naissance_deliveryman_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='location',
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='lat',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='long',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
